model:
  hidden_channels: 256
  encoder:
    name: egnn
    num_layers: 6
    hidden_dim: 256
    edge_dim: 0
    num_r_gaussian: 64
    act_fn: relu
    norm: False
    cutoff: 10.0
    knn: 48

train:
  seed: 2021
  batch_size: 1
  num_workers: 4
  max_epochs: 20
  early_stop_patience: 5
  report_iter: 500
  val_freq: 1
  pos_noise_std: 0.1
  max_grad_norm: 10.
  optimizer:
    type: adam
    lr: 3.e-4
    weight_decay: 0
    beta1: 0.99
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 3
    min_lr: 1.e-5

dataset:
  name: crossdocked_affinity
  root: ./data/crossdocked_v1.1_rmsd1.0_pocket10
  split: ./data/crossdocked_pocket10_pose_split.pt
  affinity_info: ./data/affinity_info.pkl
  val_fraction: 0.1
  train_subsample: 6000
